### ISSUE TITLE
Chapter6, rocket is not worked.

### ISSUE THREAD

**Issue by gsmlg** [PacktPublishing/Network-Programming-with-Rust#4]
Cargo run, got errors bellow:
```
    Updating crates.io index
error: failed to select a version for the requirement `ring = "^0.11.0"`
  candidate versions found which didn't match: 0.16.7, 0.16.6, 0.16.5, ...
  location searched: crates.io index
required by package `cookie v0.9.1`
    ... which is depended on by `rocket v0.3.5`
    ... which is depended on by `rocket-blog v0.1.0
```

**Comment by AdamW666** [comment]
Change to rocket 0.4.2 can resolve the problem.

**Comment by ManikandanKurup-Packt** [comment]
Hi @gsmlg, has the issue been resolved?

**Comment by gsmlg** [comment]
Update rocket to 0.4.2, and got this:
```
   Compiling pear_codegen v0.1.4
   Compiling rocket_codegen v0.4.5
   Compiling rocket v0.4.5
   Compiling bitflags v1.2.1
error: failed to run custom build command for `pear_codegen v0.1.4`

Caused by:
  process didn't exit successfully: `/var/lib/git/Network-Programming-with-Rust/Chapter06/ch6/rocket-blog/target/debug/build/pear_codegen-bc69bad7a0c3357d/build-script-build` (exit code: 101)
  --- stderr
  Error: Pear requires a 'dev' or 'nightly' version of rustc.
  Installed version: 1.46.0 (2020-08-24)
  Minimum required:  1.31.0-nightly (2018-10-05)
  thread 'main' panicked at 'Aborting compilation due to incompatible compiler.', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/pear_codegen-0.1.4/build.rs:24:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by gsmlg** [comment]
```
   Compiling pear_codegen v0.1.4
   Compiling rocket_codegen v0.4.5
   Compiling rocket v0.4.5
   Compiling hashbrown v0.8.2
error: failed to run custom build command for `pear_codegen v0.1.4`

Caused by:
  process didn't exit successfully: `/var/lib/git/Network-Programming-with-Rust/Chapter06/ch6/rocket-blog/target/debug/build/pear_codegen-bc69bad7a0c3357d/build-script-build` (exit code: 101)
  --- stderr
  Error: Pear requires a 'dev' or 'nightly' version of rustc.
  Installed version: 1.46.0 (2020-08-24)
  Minimum required:  1.31.0-nightly (2018-10-05)
  thread 'main' panicked at 'Aborting compilation due to incompatible compiler.', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/pear_codegen-0.1.4/build.rs:24:13
  stack backtrace:
     0:     0x55c633c6a665 - backtrace::backtrace::libunwind::trace::h14d338b30b3ea0a7
                                 at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
     1:     0x55c633c6a665 - backtrace::backtrace::trace_unsynchronized::h73ea91d74a3fd67f
                                 at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
     2:     0x55c633c6a665 - std::sys_common::backtrace::_print_fmt::hd42948c952866e12
                                 at src/libstd/sys_common/backtrace.rs:78
     3:     0x55c633c6a665 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha8f928866ff7571e
                                 at src/libstd/sys_common/backtrace.rs:59
     4:     0x55c633c8c3bc - core::fmt::write::he0c1e5f7426d2718
                                 at src/libcore/fmt/mod.rs:1076
     5:     0x55c633c67ce2 - std::io::Write::write_fmt::hf3afc6cfd57d0033
                                 at src/libstd/io/mod.rs:1537
     6:     0x55c633c6caa0 - std::sys_common::backtrace::_print::hfc0110703f3696fd
                                 at src/libstd/sys_common/backtrace.rs:62
     7:     0x55c633c6caa0 - std::sys_common::backtrace::print::h3f77c6990ddfaa22
                                 at src/libstd/sys_common/backtrace.rs:49
     8:     0x55c633c6caa0 - std::panicking::default_hook::{{closure}}::heae49580a8d62d75
                                 at src/libstd/panicking.rs:198
     9:     0x55c633c6c7ec - std::panicking::default_hook::hecc34e3f729e213c
                                 at src/libstd/panicking.rs:217
    10:     0x55c633c6d0e3 - std::panicking::rust_panic_with_hook::he82f5d0644692441
                                 at src/libstd/panicking.rs:526
    11:     0x55c633c46e15 - std::panicking::begin_panic::hc70e4171301eaefb
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:456
    12:     0x55c633c42995 - build_script_build::main::h4705302db081dfc4
                                 at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/pear_codegen-0.1.4/build.rs:24
    13:     0x55c633c4451b - std::rt::lang_start::{{closure}}::ha1057906b5bf4539
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:67
    14:     0x55c633c6d4b3 - std::rt::lang_start_internal::{{closure}}::h5d3ea623498f5f43
                                 at src/libstd/rt.rs:52
    15:     0x55c633c6d4b3 - std::panicking::try::do_call::hac65e71be769a440
                                 at src/libstd/panicking.rs:348
    16:     0x55c633c6d4b3 - std::panicking::try::hd4706e264bcf6712
                                 at src/libstd/panicking.rs:325
    17:     0x55c633c6d4b3 - std::panic::catch_unwind::h948a0fb4a8b3ee82
                                 at src/libstd/panic.rs:394
    18:     0x55c633c6d4b3 - std::rt::lang_start_internal::h72cc068ed2d0ac53
                                 at src/libstd/rt.rs:51
    19:     0x55c633c444f7 - std::rt::lang_start::h5b81fc4565fb5fd6
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:67
    20:     0x55c633c4319a - main
    21:     0x7fc8306190b3 - __libc_start_main
    22:     0x55c633c4217e - _start
    23:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by achanda** [comment]
Sorry for the late reply @gsmlg. I have fixed these errors now. Please pull in master again and build.
